services:
  web:
    platform: linux/arm64
    build:
      context: .
      platforms:
        - linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
